### ISSUE TITLE
Linux kernel 3.15

### ISSUE THREAD

**Issue by gsstudios** [dragonGR/Dorimanx-SG2-I9100-Kernel#1]
It seems that your kernel is on kernel version 3.14. 

This is because the repo was forked from Dori and not Computonio's. 

I will help update the kernel to bring it to match other Dori kernels.

**Comment by gsstudios** [comment]
Part 1 of linux kernel update merge: https://github.com/dragonGR/Dorimanx-SG2-I9100-Kernel/pull/7

**Comment by dragonGR** [comment]
Done.
