### ISSUE TITLE
Blank SD or unsupported format after format

### ISSUE THREAD

**Issue by dragonGR** [dragonGR/Dorimanx-SG2-I9100-Kernel#13]
Tried to format my external sdcard(sandisk 16gb) on settings>storage after format it said "Blank SD or unsupported format after format" i fixed it after formatting it on another phone. Even the PC couldn't recognize it.

**Comment by gsstudios** [comment]
Strange. Is this with build 8.55 or with all of the recent changes? Both?

**Comment by dragonGR** [comment]
build 8.55. I'm compiling now with the recent changes. Hope this will work.

**Comment by dragonGR** [comment]
Just tested. I don't have this problem anymore, not sure why but.. it works.
