### ISSUE TITLE
Reduce kernel zip size

### ISSUE THREAD

**Issue by gsstudios** [dragonGR/Dorimanx-SG2-I9100-Kernel#2]
As of the current build, it seems that the kernel zip is quite bigger than what it should be (20MB vs 11MB). 

I will try to help reduce the size.

**Comment by dragonGR** [comment]
Any ideas? When i unzip the kernel i can see another dorimanx.zip there.. maybe something i forgot to edit on build_kernel.sh ?

**Comment by gsstudios** [comment]
I'll have a look at it later.

**Comment by gsstudios** [comment]
You're doing something wrong. Here is my screenshot of what it is supposed to look like 
![capture](https://cloud.githubusercontent.com/assets/9124784/16907789/bef7f056-4d09-11e6-940d-ee63729c1c18.PNG)

**Comment by dragonGR** [comment]
Yeah, you are right. Just cleaned up the READY-JB folder and now it shows 10MB.. i had 2 builds there :P
