### ISSUE TITLE
Sync scheduler changes 

### ISSUE THREAD

**Issue by gsstudios** [dragonGR/Dorimanx-SG2-I9100-Kernel#4]
Same story is with schedulers. 

BFQ can be updated to the current newest and other fixes can be applied over the old files. 

I will also introduce a few other schedulers and delete any broken schedulers.

**Comment by gsstudios** [comment]
It seems that BFQ update will break build on your builds. I'll have a look what's causing this issue.

**Comment by dragonGR** [comment]
BFQ errors is like rq_fifo something like that.. i tried to remove fifo but no luck, i removed fifo and vr anyway since they are junk schedulers.

**Comment by gsstudios** [comment]
Updates to schedulers completed in latest merge.
