### ISSUE TITLE
Optimize kernel init script

### ISSUE THREAD

**Issue by gsstudios** [dragonGR/Dorimanx-SG2-I9100-Kernel#6]
Currently, there are many unneeded code in the initramfs that can be safely removed or refactored in order to provide a more stable kernel. 

I will be looking out for code style errors, unused variables, etc...

**Comment by dragonGR** [comment]
Thanks a lot.

**Comment by gsstudios** [comment]
I would say most code style errors from init script has been fixed. Not much to optimize :)
