### ISSUE TITLE
Update toolchain

### ISSUE THREAD

**Issue by gsstudios** [dragonGR/Dorimanx-SG2-I9100-Kernel#9]
The current included toolchain (custom Linaro 4.8 by Dori) is old and could be updated to a newer one which could improve overall battery life and performance. You are missing a few changes but I will fix this.

**Comment by dragonGR** [comment]
linaro 4.9 is better? 
I used linaro 4.8 and no problems so far.

**Comment by gsstudios** [comment]
Linaro 4.9 is better. We should allow toolchain to be updated further and so Linaro 4.9 support is the first step.

**Comment by dragonGR** [comment]
Ok, shall i expect a new pull request ?

**Comment by gsstudios** [comment]
I think I will need a bit of a break for now :)

**Comment by dragonGR** [comment]
Ok, worries, meanwhile i will try to test all the changes you made. Thanks a lot.

**Comment by dragonGR** [comment]
All is done. Thanks @gsstudios for everything.
